version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  backend:
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI:-mongodb://mongo:27017/cafe}
      APP_JWTSECRET: ${JWT_SECRET}
      APP_JWTEXPIRATIONMS: ${JWT_EXP_MS:-86400000}
    depends_on:
      - mongo
    ports:
      - "${HTTP_PORT:-8080}:8080"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  frontend:
    image: ${FRONTEND_IMAGE}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  mongo_data:
