version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./cafe-backend
    image: cafe-backend:local
    environment:
      # Override in CI/production
      SPRING_DATA_MONGODB_URI: mongodb+srv://huuduongle2002:Duongmb8602@cluster0.andq2.mongodb.net/cafe-backend
      APP_JWTSECRET: 9u8f7e6d5c4b3a29z1y0xwvuTSrQpLmNqR2t4y6u8i0oPqRs
      APP_JWTEXPIRATIONMS: "86400000"
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./cafe-frontend
    image: cafe-frontend:local
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
