name: Build and Publish Docker images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # IMAGE_* will be computed in a step to ensure lowercase (GHCR requires lowercase repo paths)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image names (lowercase)
        run: |
          OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}
          echo "IMAGE_OWNER=${OWNER_LC}" >> $GITHUB_ENV
          echo "IMAGE_BACKEND=${OWNER_LC}/cafe-backend" >> $GITHUB_ENV
          echo "IMAGE_FRONTEND=${OWNER_LC}/cafe-frontend" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./cafe-backend
          file: ./cafe-backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:${{ github.sha }}

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./cafe-frontend
          file: ./cafe-frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:${{ github.sha }}
